### ISSUE TITLE
Invalid card payment test case problem

### ISSUE THREAD

**Issue by DmitryGolubev** [Online-Payments/sdk-java#3]
Hello.
We are testing our integration with PayOne payment system. We have encountered a problem while testing cases with invalid bank cards. We took the numbers of the invalid VISA card 4450022237973103 and tried to make a payment. As we realized, it should have ended in an error. However, we get a successful payment completion status as well as a successful refund transaction. Could you please advise what could be the problem?

Bank card details were taken from here: [Test cards](https://developer.payone.com/en/integration/how-to-integrate/test-cases/index)

Also tried VISA card 4111 1111 1111 1111 1111 1111 1111

We use arbitrary values as cvc, expiry, holder.

**Comment by online-payments-support-team** [comment]
Hello @DmitryGolubev,

Thank you for sharing the information regarding the issue but unfortunately we could not provide the right answer for your question. We had a closer look at your issue and the conclusion is that it is not related to the SDK itself, instead it is probably related to missing validations on the invalid cards provided in the request. Therefore, we suggest contacting the official [Payone support ](https://developer.payone.com/en/about/contact/index) in order to properly address this issue.

This support channel is mainly for issues regarding the SDK and we encourage you to share any other issues related to the SDK itself.

Kind regards
